import { useEffect } from "react"
import type { StoryboardItem } from "../types"
import { useAutoGenerateState } from "./auto-generate/useAutoGenerateState"
import { useAutoGenerateLogic } from "./auto-generate/useAutoGenerateLogic"

export type {
  AutoGenerateStage,
  EpisodeProgressSummary,
  EpisodeProgressState,
  ScriptEntityCatalog
} from "./auto-generate/useAutoGenerateState"

export function useAutoGenerateStoryboards(params: {
  autoGenerate?: boolean
  storyId?: string
  outlineId?: string
  outlineById: Record<string, { id: string; outlineText: string; originalText: string }> | null
  activeEpisode: string
  setItems: (items: StoryboardItem[]) => void
  reloadShots: (outlineId: string) => Promise<void>
  generateScriptForItem: (item: StoryboardItem) => Promise<unknown>
  runTasksWithConcurrency: (tasks: Array<() => Promise<void>>, concurrency: number) => Promise<void>
}) {
  const { autoGenerate, outlineById, activeEpisode } = params

  const state = useAutoGenerateState(activeEpisode)
  const handleAutoGenerate = useAutoGenerateLogic(state, params)

  const {
    isAutoGenerating,
    generationStage,
    generationEpisodeId,
    textBatchMeta,
    scriptSummary,
    promptSummary,
    assetSummary,
    episodeProgressById,
    scriptEntityCatalog,
    hasAutoGeneratedRef
  } = state

  useEffect(() => {
    if (autoGenerate && !hasAutoGeneratedRef.current && outlineById && Object.keys(outlineById).length > 0) {
      hasAutoGeneratedRef.current = true
      handleAutoGenerate()
    }
  }, [autoGenerate, outlineById, handleAutoGenerate, hasAutoGeneratedRef])

  return {
    isAutoGenerating,
    generationStage,
    generationEpisodeId,
    textBatchMeta,
    scriptSummary,
    promptSummary,
    assetSummary,
    episodeProgressById,
    scriptEntityCatalog,
    handleAutoGenerate
  }
}
