import { useRef, useState, useEffect } from "react"

export type AutoGenerateStage = "idle" | "clearing" | "storyboard_text" | "reloading" | "script" | "assets" | "done" | "error"

export type EpisodeProgressSummary = { total: number; done: number; failed: number }
export type EpisodeProgressState = {
  textStatus?: "pending" | "success" | "error"
  script?: EpisodeProgressSummary
  prompts?: EpisodeProgressSummary
  assets?: EpisodeProgressSummary
}

export type ScriptEntityCatalog = {
  background: Array<{ name: string; description: string }>
  role: Array<{ name: string; description: string }>
  item: Array<{ name: string; description: string }>
}

export function useAutoGenerateState(activeEpisode: string) {
  const [isAutoGenerating, setIsAutoGenerating] = useState(false)
  const [generationStage, setGenerationStage] = useState<AutoGenerateStage>("idle")
  const [generationEpisodeId, setGenerationEpisodeId] = useState<string>("")
  const [textBatchMeta, setTextBatchMeta] = useState<{ total: number; failed: number } | null>(null)
  const [scriptSummary, setScriptSummary] = useState<{ total: number; done: number; failed: number } | null>(null)
  const [promptSummary, setPromptSummary] = useState<{ total: number; done: number; failed: number } | null>(null)
  const [assetSummary, setAssetSummary] = useState<{ total: number; done: number; failed: number } | null>(null)
  const [episodeProgressById, setEpisodeProgressById] = useState<Record<string, EpisodeProgressState>>({})
  const [scriptEntityCatalog, setScriptEntityCatalog] = useState<ScriptEntityCatalog>({ background: [], role: [], item: [] })

  const hasAutoGeneratedRef = useRef(false)
  const activeEpisodeRef = useRef(activeEpisode)
  const entitySetsRef = useRef<{ background: Set<string>; role: Set<string>; item: Set<string> }>({
    background: new Set(),
    role: new Set(),
    item: new Set()
  })

  useEffect(() => {
    activeEpisodeRef.current = activeEpisode
  }, [activeEpisode])

  useEffect(() => {
    if (generationStage === "idle") setGenerationEpisodeId("")
  }, [generationStage])

  return {
    isAutoGenerating, setIsAutoGenerating,
    generationStage, setGenerationStage,
    generationEpisodeId, setGenerationEpisodeId,
    textBatchMeta, setTextBatchMeta,
    scriptSummary, setScriptSummary,
    promptSummary, setPromptSummary,
    assetSummary, setAssetSummary,
    episodeProgressById, setEpisodeProgressById,
    scriptEntityCatalog, setScriptEntityCatalog,
    hasAutoGeneratedRef,
    activeEpisodeRef,
    entitySetsRef
  }
}
